import {
  buildProjection,
  type Artifact,
  type Agent,
  type Locus,
  type Organization,
  type Person,
  type Room,
  type Tunnel,
  type Wing,
  type WorldGraph,
  worldRef,
} from './model'

const wingWorkGoals: Wing = {
  kind: 'wing',
  id: 'wing-work-goals',
  title: 'Work-Goals',
  summary: 'The active execution wing for DewDrops, memory palace planning, and phone relay work.',
  color: '#7f5af0',
  roomIds: ['room-launch-deck', 'room-memory-palace', 'room-phone-relay'],
  actorIds: ['person-tyler', 'organization-aibutler', 'agent-codex', 'agent-claude', 'agent-grok'],
  position: { x: 0, y: 0, z: 0 },
  tags: ['home', 'execution', 'crm'],
}

const tyler: Person = {
  kind: 'person',
  id: 'person-tyler',
  title: 'Tyler Steeves',
  summary: 'Primary operator and relationship anchor for the DewDrops world.',
  wingId: wingWorkGoals.id,
  roomIds: ['room-launch-deck', 'room-memory-palace', 'room-phone-relay'],
  pronouns: 'he/him',
  position: { x: -120, y: 40, z: 0 },
  tags: ['operator', 'customer'],
}

const aiButlerCompany: Organization = {
  kind: 'organization',
  id: 'organization-aibutler',
  title: 'aiButler Prototype Company',
  summary: 'The live execution organization that anchors the active CRM room graph.',
  wingId: wingWorkGoals.id,
  roomIds: ['room-launch-deck', 'room-memory-palace'],
  memberActorIds: ['person-tyler', 'agent-codex', 'agent-claude'],
  position: { x: 80, y: 36, z: 0 },
  tags: ['company', 'crm', 'prototype'],
}

const codex: Agent = {
  kind: 'agent',
  id: 'agent-codex',
  title: 'Codex',
  summary: 'Implementation agent for heavy engineering sessions.',
  wingId: wingWorkGoals.id,
  roomIds: ['room-launch-deck', 'room-memory-palace', 'room-phone-relay'],
  provider: 'codex',
  active: true,
  position: { x: 180, y: -20, z: 0 },
  tags: ['implementation', 'engineering'],
}

const claude: Agent = {
  kind: 'agent',
  id: 'agent-claude',
  title: 'Claude',
  summary: 'Reasoning agent for synthesis, critique, and product framing.',
  wingId: wingWorkGoals.id,
  roomIds: ['room-launch-deck', 'room-memory-palace', 'room-phone-relay'],
  provider: 'claude',
  active: true,
  position: { x: 210, y: 110, z: 0 },
  tags: ['reasoning', 'product'],
}

const grok: Agent = {
  kind: 'agent',
  id: 'agent-grok',
  title: 'Grok',
  summary: 'Exploration agent for broad context and alternate framing.',
  wingId: wingWorkGoals.id,
  roomIds: ['room-memory-palace'],
  provider: 'grok',
  active: false,
  position: { x: 200, y: 220, z: 0 },
  tags: ['exploration', 'research'],
}

const launchDeck: Room = {
  kind: 'room',
  id: 'room-launch-deck',
  title: 'Launch Deck',
  summary: 'The room for goals, launches, and active swarm control.',
  wingId: wingWorkGoals.id,
  actorIds: [tyler.id, aiButlerCompany.id, codex.id, claude.id],
  locusIds: ['locus-north-star', 'locus-control-surface', 'locus-inbox-compartment'],
  artifactIds: ['artifact-roadmap', 'artifact-launch-brief'],
  tunnelIds: ['tunnel-context', 'tunnel-device'],
  position: { x: 0, y: 0, z: 0 },
  tone: 'intentional',
  tags: ['launch', 'goals', 'control'],
}

const memoryPalace: Room = {
  kind: 'room',
  id: 'room-memory-palace',
  title: 'Memory Palace',
  summary: 'A visual context room for durable recall and structured compression.',
  wingId: wingWorkGoals.id,
  actorIds: [tyler.id, claude.id, grok.id],
  locusIds: ['locus-origin-gate', 'locus-people-wall', 'locus-evidence-desk', 'locus-future-window'],
  artifactIds: ['artifact-moonwalking-notes'],
  tunnelIds: ['tunnel-context', 'tunnel-recall'],
  position: { x: 320, y: -20, z: 0 },
  tone: 'reflective',
  tags: ['memory', 'context', 'recall'],
}

const phoneRelay: Room = {
  kind: 'room',
  id: 'room-phone-relay',
  title: 'Phone Relay',
  summary: 'A compact room for mobile execution and quick confirmations.',
  wingId: wingWorkGoals.id,
  actorIds: [tyler.id, codex.id, claude.id],
  locusIds: ['locus-android-port', 'locus-iphone-port', 'locus-network-shelf'],
  artifactIds: ['artifact-phone-prototype'],
  tunnelIds: ['tunnel-device', 'tunnel-recall'],
  position: { x: 180, y: 220, z: 0 },
  tone: 'compact',
  tags: ['phone', 'relay', 'mobile'],
}

const loci = [
  {
    kind: 'locus',
    id: 'locus-north-star',
    title: 'North Star',
    summary: 'The primary mission anchor for the room.',
    roomId: launchDeck.id,
    locusKind: 'platform',
    actorIds: [tyler.id],
    artifactIds: ['artifact-roadmap'],
    position: { x: -220, y: -80, z: 0 },
    tags: ['mission'],
  },
  {
    kind: 'locus',
    id: 'locus-control-surface',
    title: 'Control Surface',
    summary: 'The active agent control strip.',
    roomId: launchDeck.id,
    locusKind: 'console',
    actorIds: [codex.id, claude.id],
    artifactIds: ['artifact-launch-brief'],
    position: { x: 0, y: -120, z: 0 },
    tags: ['agents', 'control'],
  },
  {
    kind: 'locus',
    id: 'locus-inbox-compartment',
    title: 'Inbox Compartment',
    summary: 'Open questions and waiting items live here.',
    roomId: launchDeck.id,
    locusKind: 'compartment',
    actorIds: [tyler.id],
    artifactIds: [],
    position: { x: 220, y: -40, z: 0 },
    tags: ['inbox', 'pending'],
  },
  {
    kind: 'locus',
    id: 'locus-origin-gate',
    title: 'Origin Gate',
    summary: 'The doorway into a remembered sequence.',
    roomId: memoryPalace.id,
    locusKind: 'door',
    actorIds: [tyler.id],
    artifactIds: ['artifact-moonwalking-notes'],
    position: { x: -180, y: 0, z: 0 },
    tags: ['entry'],
  },
  {
    kind: 'locus',
    id: 'locus-people-wall',
    title: 'People Wall',
    summary: 'People and relationships compress into a stable spatial strip.',
    roomId: memoryPalace.id,
    locusKind: 'wall',
    actorIds: [tyler.id, claude.id, grok.id],
    artifactIds: [],
    position: { x: 0, y: -100, z: 0 },
    tags: ['relationships'],
  },
  {
    kind: 'locus',
    id: 'locus-evidence-desk',
    title: 'Evidence Desk',
    summary: 'Proof, notes, and documents stay within reach.',
    roomId: memoryPalace.id,
    locusKind: 'table',
    actorIds: [claude.id],
    artifactIds: ['artifact-moonwalking-notes'],
    position: { x: 0, y: 80, z: 0 },
    tags: ['evidence'],
  },
  {
    kind: 'locus',
    id: 'locus-future-window',
    title: 'Future Window',
    summary: 'Opportunities and next moves stay visible.',
    roomId: memoryPalace.id,
    locusKind: 'window',
    actorIds: [grok.id],
    artifactIds: [],
    position: { x: 200, y: -20, z: 0 },
    tags: ['future'],
  },
  {
    kind: 'locus',
    id: 'locus-android-port',
    title: 'Android Port',
    summary: 'The mobile device handoff point for Android testing.',
    roomId: phoneRelay.id,
    locusKind: 'console',
    actorIds: [codex.id],
    artifactIds: ['artifact-phone-prototype'],
    position: { x: -160, y: 0, z: 0 },
    tags: ['android'],
  },
  {
    kind: 'locus',
    id: 'locus-iphone-port',
    title: 'iPhone Port',
    summary: 'The mobile device handoff point for iPhone testing.',
    roomId: phoneRelay.id,
    locusKind: 'console',
    actorIds: [claude.id],
    artifactIds: ['artifact-phone-prototype'],
    position: { x: 0, y: -90, z: 0 },
    tags: ['iphone'],
  },
  {
    kind: 'locus',
    id: 'locus-network-shelf',
    title: 'Network Shelf',
    summary: 'The network and reliability references are stored here.',
    roomId: phoneRelay.id,
    locusKind: 'archive',
    actorIds: [tyler.id],
    artifactIds: [],
    position: { x: 180, y: 0, z: 0 },
    tags: ['network', 'reliability'],
  },
] satisfies Locus[]

const artifacts: Artifact[] = [
  {
    kind: 'artifact',
    id: 'artifact-roadmap',
    title: 'Work-Goals Roadmap',
    summary: 'A compact plan for the active DewDrops work sequence.',
    roomId: launchDeck.id,
    locusId: 'locus-north-star',
    artifactKind: 'plan',
    actorIds: [tyler.id, aiButlerCompany.id],
    position: { x: -240, y: -160, z: 0 },
    tags: ['plan', 'roadmap'],
  },
  {
    kind: 'artifact',
    id: 'artifact-launch-brief',
    title: 'Launch Brief',
    summary: 'The current execution brief for agents and operators.',
    roomId: launchDeck.id,
    locusId: 'locus-control-surface',
    artifactKind: 'document',
    actorIds: [codex.id, claude.id],
    position: { x: 100, y: -140, z: 0 },
    tags: ['brief', 'launch'],
  },
  {
    kind: 'artifact',
    id: 'artifact-moonwalking-notes',
    title: 'Moonwalking Notes',
    summary: 'Memory-palace notes distilled into readable structure.',
    roomId: memoryPalace.id,
    locusId: 'locus-evidence-desk',
    artifactKind: 'note',
    actorIds: [tyler.id],
    position: { x: -120, y: 100, z: 0 },
    tags: ['memory', 'book'],
  },
  {
    kind: 'artifact',
    id: 'artifact-phone-prototype',
    title: 'Phone Prototype',
    summary: 'A working mobile relay prototype for Android and iPhone inspection.',
    roomId: phoneRelay.id,
    locusId: 'locus-android-port',
    artifactKind: 'model',
    actorIds: [codex.id, claude.id],
    position: { x: 160, y: 140, z: 0 },
    tags: ['phone', 'prototype'],
  },
]

const tunnels: Tunnel[] = [
  {
    kind: 'tunnel',
    id: 'tunnel-context',
    from: worldRef('room', launchDeck.id),
    to: worldRef('room', memoryPalace.id),
    label: 'context',
    summary: 'Launch work feeds the memory palace and the palace returns durable context.',
    tunnelKind: 'memory',
    tags: ['context', 'memory'],
  },
  {
    kind: 'tunnel',
    id: 'tunnel-device',
    from: worldRef('room', launchDeck.id),
    to: worldRef('room', phoneRelay.id),
    label: 'device relay',
    summary: 'The launch deck projects a compact relay into the phone room.',
    tunnelKind: 'route',
    tags: ['device', 'mobile'],
  },
  {
    kind: 'tunnel',
    id: 'tunnel-recall',
    from: worldRef('room', memoryPalace.id),
    to: worldRef('room', phoneRelay.id),
    label: 'recall',
    summary: 'The memory palace and the phone relay share the same compact reference pack.',
    tunnelKind: 'handoff',
    tags: ['recall', 'handoff'],
  },
]

export const seedWorldGraph: WorldGraph = {
  id: 'world-dewdrops',
  title: 'DewDrops World',
  summary: 'A first World OS seed for DewDrops: one wing, several actors, rooms, loci, and tunnels.',
  entryWingId: wingWorkGoals.id,
  entryRoomId: launchDeck.id,
  wings: [wingWorkGoals],
  actors: [tyler, aiButlerCompany, codex, claude, grok],
  rooms: [launchDeck, memoryPalace, phoneRelay],
  loci,
  artifacts,
  tunnels,
}

export const seedWorldProjection = buildProjection(seedWorldGraph, worldRef('room', launchDeck.id), 'room')
